{
 "title": "Admin Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Down Node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(up==0)", "legendFormat": "Down Nodes" }
   ]
  },
  {
   "title": "Up Node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up==1)", "legendFormat": "Down Nodes" }
   ]
  },
  {
   "title": "Nodes By JOB",
   "type": "stat",
   "gridPos": { "h": 23, "w": 17, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(up) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Down Nodes in Promethteus",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 4 },
   "targets": [
    { "expr": "up == 0" }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ALERTS{alertname!=\"DeadMansSwitch\",alertstate='firing'} > 0"
    }
   ]
  },
  {
   "title": "UP Nodes in Promethteus",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "targets": [
    { "expr": "up == 1" }
   ]
  }
 ]
}