{
 "title": "gCore-Asset-ping",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime Percentage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"gCore-Ping\"}[$__range]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VXLAN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"gCore-Ping\",instance=~\"172.16.110.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"gCore-Ping\",instance=~\"172.16.109.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Management",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"gCore-Ping\",instance=~\"172.16.104.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "All Range",
   "type": "state-timeline",
   "gridPos": { "h": 57, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "probe_success{job=\"gCore-Ping\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}