{
 "title": "Product Team Libvirt Dashboard",
 "description": "Dashboard For Libvirt Optimized By Soroush Kaviani",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,15s,30s,1m,2m,5m,15m,30m,1h,2h,1d"
   },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{job=\"prometheus-libvirt-exporter\"}, host)"
    }
   },
   {
    "name": "virtual_machine",
    "label": "VM",
    "query": {
     "query": "label_values(libvirt_domain_state_code{host=~\"$compute\", job=\"prometheus-libvirt-exporter\"}, domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Libvirt Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libvirt_domains_number{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "No State VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"gc.*|release.*\"} ==0)",
     "legendFormat": "Suspend"
    }
   ]
  },
  {
   "title": "Running VMs GPortal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\" , projectName =~\"gc.*\" } ==1)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Running VMs  Gportal Release",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\" , projectName =~\"release.*\" } ==1)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Running VMs IranServer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\" , projectName =~\"iranserver.*\" } ==1)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "vCPU Usage on VM",
   "type": "timeseries",
   "description": "100% = 1 Thread",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "avg by (domain) (irate(libvirt_domain_info_cpu_time_seconds_total{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"prometheus-libvirt-exporter\"}[30s])) * 100",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Crashed VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"gc.*|release.*\"} ==6)",
     "legendFormat": "Shut Off"
    }
   ]
  },
  {
   "title": "Shut Off VMs GPortal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\" , projectName =~\"gc.*\" } ==5)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Shut Off VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"release.*\"} ==5)",
     "legendFormat": "Shut Off"
    }
   ]
  },
  {
   "title": "Shut Off VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"iranserver.*\"} ==5)",
     "legendFormat": "Shut Off"
    }
   ]
  },
  {
   "title": "Suspend VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"gc.*|release.*\"} ==3)",
     "legendFormat": "Suspend"
    }
   ]
  },
  {
   "title": "RD and Blockchian and GreenWebPlus and cdn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\" , projectName =~\"GreenWebPlus.*|blockchain.*|cdn.*|ehsan-sandbox.*\" } ==1)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "gcore team",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\" , projectName =~\"GreenwebCloud.*|admin.*|ali.*|moghadasi.*\" } ==1)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "All Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Data Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Project Instance",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (projectName) (libvirt_domain_state_code)",
     "legendFormat": "{{projectName}}"
    }
   ]
  },
  {
   "title": "VMs Stats",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"gc.*|release.*\"}-0",
     "legendFormat": "vCPU Total"
    },
    {
     "expr": "(avg by (domain) (irate(libvirt_domain_info_cpu_time_seconds_total{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"gc.*|release.*\"}[30s])) * 100)-0",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"gc.*|release.*\"}-0",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "(libvirt_domain_info_maximum_memory_bytes{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"gc.*|release.*\"} - libvirt_domain_stat_memory_unused_bytes{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"gc.*|release.*\"})-0",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "libvirt_domain_state_code{host=~\"$compute\", job=~\"prometheus-libvirt-exporter\", projectName =~\"gc.*|release.*\"}",
     "legendFormat": "Status"
    }
   ]
  }
 ]
}